version: '3'
services:
  php:
    image: bykclk/php-symfony
    ports:
      - 9000:9000
    volumes:
      - ./:/app/
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      APP_ENV: dev
      APP_SECRET: "CHANGE_ME"
  nginx:
    image: nginx:1.17.8
    ports:
      - 80:80
    volumes:
      - ./:/app/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  node:
    image: node:13
    volumes:
      - ./:/app/
    working_dir: /app